### ISSUE TITLE
Error running process

### ISSUE THREAD

**Issue by Vennaya** [MarcusNyne/sd-scramble-prompts-m9#21]
When trying to use this, i get the following error in the terminal

```
*** Error running process: E:\AI 2024\stable-diffusion-webui-directml\extensions\sd-scramble-prompts-m9\scripts\scramble_prompts.py
    Traceback (most recent call last):
      File "E:\AI 2024\stable-diffusion-webui-directml\modules\scripts.py", line 832, in process
        script.process(p, *script_args)
      File "E:\AI 2024\stable-diffusion-webui-directml\extensions\sd-scramble-prompts-m9\scripts\scramble_prompts.py", line 112, in process
        opts.data['directories_filename_pattern'] = self.__calc_dirpattern(chk_variation_folders, self._cnt_variations-1)
      File "E:\AI 2024\stable-diffusion-webui-directml\extensions\sd-scramble-prompts-m9\scripts\scramble_prompts.py", line 134, in __calc_dirpattern
        elif self.__is_none(self._original_dirpattern):
    AttributeError: 'Script' object has no attribute '_original_dirpattern'
```

I installed this through the extensions tab within the Automatic1111 webui, and restarted it as expected.

**Comment by MarcusNyne** [comment]
@Vennaya , thank you for reporting this issue.  I was able to reproduce something similar and am looking at the problem now.  Can you please tell me if this is your first time using the extension, or if it was working at one time and stopped working?  Thank you again for making me aware of this issue.

**Comment by MarcusNyne** [comment]
@Vennaya , thank you for reporting this issue!  The problem has been addressed.  This resulted from a new installation where settings were never applied.  To correct this problem, please save your settings or simply update the extension.  Thank you!
